apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: foobar-nginx
  name: foobar-nginx
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: foobar-nginx
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: foobar-nginx
